### ISSUE TITLE
CSV text shouldn't be URL encoded

### ISSUE THREAD

**Issue by rogargon** [raultds/TFG-RDF-Transformer-API#2]
https://github.com/raultds/TFG-RDF-Transformer-API/blob/90fef990df194ce812d6b6d9ffe52e21a66b41d2/src/main/java/com/tfg/utils/CsvReader.java#L61

This line isn't needed because if the cell is mapped to text, there is no need to URL encode it replacing spaces. This is just done if mapped to Resource. It might be the case that Jena takes care of encoding the URL if needed

**Comment by raultds** [comment]
Now it only encodes the resources
