### ISSUE TITLE
Process value if it should be interpreted as Resource URI

### ISSUE THREAD

**Issue by rogargon** [raultds/TFG-RDF-Transformer-API#5]
https://github.com/raultds/TFG-RDF-Transformer-API/blob/477f7a660e5f9f5bd9243daed3be3e18e29a6b3c/src/main/java/com/tfg/services/RDFService.java#L180

Instead of generating the resource from the cell value, check if it is already a URI (create new URI(value), if there is exception, it is not a URI). In case it is not a URI, concatenate `request.uri` and the value, like it is done with the subject. 

Test also cases where there are spaces in value, Jena should take care of them and URL encode them

**Comment by raultds** [comment]
Fixed. Now checking before creating a resource if it already exists one with that uri
